### ISSUE TITLE
ZauBot - Align topic names between simulation and real

### ISSUE THREAD

**Issue by miguelriemoliveira** [JorgeFernandes-Git/zau_bot#19]
Hi @JorgeFernandes-Git , @sergiodmlteixeira  and @rarrais ,

I noticed some things about the real ZauBot bagfile I have some suggestions:

The simulation be as close to the real robotic system as possible. 
In particular, **the topic names and link names should match** between the simulation and the real robot.

In the simulation we have the following topics (from [here](https://github.com/JorgeFernandes-Git/zau_bot/blob/main/e6_multi_modal/e6_mm_calibration/calibration/config.yml)):

```yaml
  camera:
    link: "camera_rgb_optical_frame"
    parent_link: "camera_link"
    child_link: "camera_rgb_frame"
    topic_name: "/camera/rgb/image_raw"
    throttle: 10
    modality: "rgb"

  camera_mb:
    link: "camera_mb_rgb_optical_frame"
    parent_link: "camera_mb_link"
    child_link: "camera_mb_rgb_frame"
    topic_name: "/camera_mb/rgb/image_raw"
    throttle: 10
    modality: rgb


  velodyne:
    link: "velodyne"
    parent_link: "base_link_mb"
    child_link: "velodyne_base_link"      
    topic_name: "/velodyne_points"
    modality: "lidar3d"

# ATOM will calibrate the extrinsic parameters of your links.
# In this section you should discriminate the additional transformations that will be part of the calibrations.
# NOTE: Delete the "" after additional_tfs to prevent the error 'All mapping items must start at the same column YAML'
additional_tfs:
  base_link_mb_to_base_link:
    parent_link: "base_link_mb"
    child_link: "base_link"

```

and in the bagfile we have:

```
➜  zaubot rostopic list 
/camera/color/camera_info
/camera/color/image_raw/compressed
/clicked_point
/clock
/initialpose
/joint_states
/move_base_simple/goal
/rosout
/rosout_agg
/tf
/tf_static
```

and I suspect that the tf link names are also not consistent.

We should work to make all of topic names and link names consistent between the real and the simulation. Only later we can take a bagfile and calibrate using the same calibration.yaml.

It is possible to just forget about standardizing names and create two different calibration packages for tsimulation and the real, but that's not ideal as we will never have the same robotic system.

Those would not be digital twins ... at most digital distant cousins :).

Do you think its possible to work on this? Not sure, but given that the simulation already has many results the best would be to change the zaubot drivers (BTW, where is the zaubot repo to bringup the system?) to match the simulation, instead of the opposite.

What do you think?
